CC = gcc
CFLAGS = -ansi -Wall -Wextra -Werror -pedantic-errors
SRC = $(wildcard *.c)
OBJ = $(SRC:.c=.o)
EXECUTABLE = symnmf

all: $(EXECUTABLE)

$(EXECUTABLE): $(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $(EXECUTABLE)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ) $(EXECUTABLE)

.PHONY: all clean
